version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: app_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: app_client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api
    restart: unless-stopped