services:
  db:
    image: bitnami/postgresql:16
    container_name: app_db
    environment:
      POSTGRESQL_USERNAME: appuser
      POSTGRESQL_PASSWORD: apppass
      POSTGRESQL_DATABASE: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.18.0-alpine
    container_name: app_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # Remove JWT_SECRET from here - only from .env file
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_NAME=appdb
      # Database password should come from .env file
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.18.0-alpine
    container_name: app_client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data: